/**
 * QZ Tray signing service.
 *
 * Requires an authenticated app user — only logged-in POS staff should be
 * able to request challenge signatures. The browser receives only the public
 * cert and signatures; the private key never leaves the backend.
 *
 * Supports both PKCS#8 ("-----BEGIN PRIVATE KEY-----") and PKCS#1
 * ("-----BEGIN RSA PRIVATE KEY-----") private key formats.
 */

import { createClientFromRequest } from "npm:@base44/sdk@0.8.44";

function base64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return bytes;
}

function bytesToBase64(bytes: Uint8Array): string {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

/** Build a DER length-prefixed tag (tag + length header + content). */
function derTagged(tag: number, content: number[]): number[] {
  const len = content.length;
  let header: number[];
  if (len < 0x80) header = [len];
  else if (len < 0x100) header = [0x81, len];
  else if (len < 0x10000) header = [0x82, (len >> 8) & 0xff, len & 0xff];
  else header = [0x83, (len >> 16) & 0xff, (len >> 8) & 0xff, len & 0xff];
  return [tag, ...header, ...content];
}

/**
 * Wrap a PKCS#1 RSAPrivateKey DER into a PKCS#8 PrivateKeyInfo DER, so
 * Web Crypto's importKey("pkcs8", ...) can consume keys generated by
 * `openssl genrsa` (which outputs PKCS#1).
 */
function wrapPkcs1ToPkcs8(pkcs1: Uint8Array): Uint8Array {
  // AlgorithmIdentifier: SEQUENCE { OID rsaEncryption (1.2.840.113549.1.1.1), NULL }
  const algOid = [0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00];
  const algSequence = derTagged(0x30, algOid);
  const version = [0x02, 0x01, 0x00];
  const octetString = derTagged(0x04, Array.from(pkcs1));
  const inner = [...version, ...algSequence, ...octetString];
  const outer = derTagged(0x30, inner);
  return new Uint8Array(outer);
}

Deno.serve(async (req) => {
  try {
    // Require an authenticated app user
    const client = createClientFromRequest(req);
    try {
      await client.auth.me();
    } catch {
      return Response.json({ error: "Authentication required" }, { status: 401 });
    }

    const body = await req.json().catch(() => ({}));
    const { action, toSign } = body || {};

    const cert = Deno.env.get("QZ_TRAY_CERTIFICATE");
    const privateKeyPem = Deno.env.get("QZ_TRAY_PRIVATE_KEY");

    if (!cert || !privateKeyPem) {
      return Response.json(
        { error: "QZ Tray signing not configured. Set QZ_TRAY_CERTIFICATE and QZ_TRAY_PRIVATE_KEY secrets." },
        { status: 503 }
      );
    }

    if (action === "getCert") {
      return Response.json({ certificate: cert });
    }

    if (action === "sign" && toSign) {
      const isPkcs1 = /-----BEGIN RSA PRIVATE KEY-----/.test(privateKeyPem);
      const b64 = privateKeyPem.replace(/-----[^-]+-----/g, "").replace(/\s/g, "");
      let der = base64ToBytes(b64);
      if (isPkcs1) der = wrapPkcs1ToPkcs8(der);

      const key = await crypto.subtle.importKey(
        "pkcs8",
        der,
        { name: "RSASSA-PKCS1-v1_5", hash: "SHA-512" },
        false,
        ["sign"]
      );

      const signature = await crypto.subtle.sign(
        "RSASSA-PKCS1-v1_5",
        key,
        new TextEncoder().encode(toSign)
      );

      return Response.json({ signature: bytesToBase64(new Uint8Array(signature)) });
    }

    return Response.json({ error: "Invalid action. Use 'getCert' or 'sign'." }, { status: 400 });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});